version: '3'

services:
  languagetool:
    image: erikvl87/languagetool
    container_name: languagetool
    ports:
      - "8010:8010"
    environment:
      - langtool_languageModel=/ngrams   # OPTIONAL: Using ngrams data
      - Java_Xms=512m                    # OPTIONAL: Setting a minimal Java heap size of 512 mib
      - Java_Xmx=1g                      # OPTIONAL: Setting a maximum Java heap size of 1 Gib
    volumes:
      - ./ngrams:/ngrams
      - ./en_spelling_additions.txt:/org/languagetool/resource/en/hunspell/spelling.txt
      - ./en_ignore_additions.txt:/org/languagetool/resource/en/hunspell/ignore.txt
      - ./en_prohibited_additions.txt:/org/languagetool/resource/en/hunspell/prohibited.txt
    restart: unless-stopped
